export const COURSES_ACTION_TYPES = {
	SET_ALL_COURSES_DATA: 'courses/SET_ALL_COURSES_DATA',
	CREATE_NEW_COURSE: 'courses/CREATE_NEW_COURSE',
	CLEAR_COURSES: 'courses/CLEAR_COURSES',
	ADD_NEW_MODULE: 'courses/ADD_NEW_MODULE',
	ADD_NEW_CHAPTER: 'courses/ADD_NEW_CHAPTER',
	EDIT_CHAPTER: 'courses/EDIT_CHAPTER',
};
